language: node_js
node_js:
  - "0.12"
before_install:
  - "PATH=$PATH:$HOME/.meteor"
  - "curl https://install.meteor.com/ | sh"
services:
  - mongodb
notifications:
  slack: podicus:ktZkwS7LenGrezCeNto7I4Zq
script:
  - meteor run --test