language: node_js
node_js:
  - "0.12"
before_install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-laika/master/configure.sh | /bin/sh"
services:
  - mongodb
notifications:
  slack: podicus:ktZkwS7LenGrezCeNto7I4Zq
script:
  - meteor run --test